import './globals.css';
import Head from 'next/head';
import React, {ReactNode} from 'react';

type Metadata = {
    title: string;
    description: string;
};

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode;
}) {
    const metadata: Metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
    };

    return (
        <html lang="en">
        <Head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description}/>
        </Head>
        <body>
        {children}
        </body>
        </html>
    );
}
